name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull the repo
        uses: actions/checkout@v2
      - name: install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: setup tests with pytest
        run: |
          pip install pytest
          pytest -s -v

